### PR TITLE
0.4

### PR DESCRIPTION
**Pull request by cboden**
This has been ready for a while but I haven't done it yet because the documentation hasn't been updated (which I've dragged my feet with [sorry]). From the changelog:

 * BC: $conn->WebSocket->request replaced with $conn->httpRequest which is a PSR-7 object
 * Binary messages now supported via Ratchet\WebSocket\MessageComponentInterface
 * Added heartbeat support via ping/pong in WsServer
 * BC: No longer support old (and insecure) Hixie76 and Hybi protocols
 * BC: No longer support disabling UTF-8 checks
 * BC: The Session component implements HttpServerInterface instead of WsServerInterface
 * BC: PHP 5.3 no longer supported
 * BC: Use react/socket 0.5
 * Significant performance enhancements

I'm still considering moving Sessions and WAMP to their own repo's instead of being included in core. I may or may not defer this to 0.5. 

In the mean time I feel this is ready to go, feel free to test and report bugs (and PR's 😄) against it. If there are no issues I will release when I finish updated the website's documentation.

### CODE REVIEW

**Comment by alcalyn** [comment]
Wow, merged while I was writing this comment !

I am testing this 0.4 version. I'm getting stuck with `Ratchet\Server\IoServer`.

I was doing this in the version 0.3:

``` php
$socket = new ReactSocketServer($this->loop);
$socket->listen($websocketPort, $websocketBind);

new IoServer(
    new HttpServer(
        new WsServer(
            new ServerProtocol(
                $myWampServerInterface
            )
        )
    ),
    $socket
);
```

And I'm getting this error:

```
Too few arguments to function React\Socket\Server::__construct(), 1 passed in /.../src/Websocket/Server.php on line 52 and at least 2 expected in /.../vendor/react/socket/src/Server.php:12
```

I've seen it changed, I have to pass `$uri` params, but I don't find where I can know what to set in the PR.

**Comment by cboden** [comment]
React/Socket change it's API between Ratchet 0.3 and 0.4. The parameters go in the constructor now:
```php
$socket = new ReactSocketServer($websocketBind . ':' . $webSocketPort, $this->loop);
```

**Comment by alcalyn** [comment]
Well thanks it worked, I just remove the `->listen` and move parameter like you said.

Thanks for the work on the `0.4` !
